# Generated by Django 4.2.4 on 2023-08-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Groceries', 'Groceries'), ('Home & Lifestyle', 'Home & Lifestyle')], max_length=255),
        ),
    ]
